# Generated by Django 5.0.3 on 2024-05-19 03:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Player",
            new_name="Trainer",
        ),
    ]
