# Generated by Django 5.0.3 on 2024-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_player_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
