# Generated by Django 5.0.3 on 2024-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pokemon_types_pokemon_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_types',
            name='pokemon_types',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
