# Generated by Django 5.0.3 on 2024-05-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_pokemon_prokemon_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="pokedex",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.pokemon"
            ),
        ),
    ]
