# Generated by Django 5.0.3 on 2024-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_trainer_pokedex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="pokedex",
        ),
        migrations.AddField(
            model_name="trainer",
            name="pokedex",
            field=models.ManyToManyField(
                null=True, related_name="pokemon", to="app.pokemon"
            ),
        ),
    ]
