# Generated by Django 5.0.3 on 2024-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_trainer_pokedex_trainer_pokedex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='prokemon_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
