# Generated by Django 5.0.3 on 2024-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_pokemon_prokemon_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/001.png', null=True, upload_to=''),
        ),
    ]
