# Generated by Django 5.0.3 on 2024-05-21 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_trainer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='nickname',
            field=models.CharField(default=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
