# Generated by Django 5.0.3 on 2024-05-22 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_rename_prokemon_pic_pokemon_pokemon_pic_pokemon_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="user",
        ),
    ]
