# Generated by Django 5.0.3 on 2024-05-22 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_pokemon_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="user",
        ),
    ]
